"""Write SM_alp_UFO parameter cards for ALP scan points.

The UFO does not expose ``g_agg`` directly. Its photon coupling is controlled by
``fa``, ``KB``, and ``KW``. Gate 1 fixes the associated-production scan
normalization to

    g_agg = alpha_em * (KB + KW) / (sqrt(2) * pi * fa)

with ``fa`` in GeV. This script lets the scan use physical ``g_agg`` while the
generated param card still varies the UFO-native parameters.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path


DEFAULT_AEWM1 = 137.035999084
DEFAULT_FA_GEV = 1000.0
DEFAULT_GF = 1.16637e-5
DEFAULT_MZ_GEV = 91.1876
ALP_PDG_ID = 9999


def alpha_em(aewm1: float = DEFAULT_AEWM1) -> float:
    return 1.0 / aewm1


def g_agg_from_ufo(fa_gev: float, kb: float, kw: float, aewm1: float = DEFAULT_AEWM1) -> float:
    """Return the production-normalized a-gamma-gamma coupling in GeV^-1."""
    return alpha_em(aewm1) * (kb + kw) / (math.sqrt(2.0) * math.pi * fa_gev)


def g_agg_width_from_ufo(fa_gev: float, kb: float, kw: float, aewm1: float = DEFAULT_AEWM1) -> float:
    """Return the coupling normalization implied directly by the UFO width."""
    return alpha_em(aewm1) * (kb + kw) / (math.pi * fa_gev)


def k_sum_from_g_agg(g_agg: float, fa_gev: float, aewm1: float = DEFAULT_AEWM1) -> float:
    """Return KB + KW required to realize ``g_agg`` at the chosen ``fa``."""
    return g_agg * math.sqrt(2.0) * math.pi * fa_gev / alpha_em(aewm1)


def width_a_to_aa(m_a_gev: float, g_agg: float) -> float:
    """Gamma(a -> gamma gamma) in GeV using L = g_agg/4 a F Ftilde."""
    return g_agg**2 * m_a_gev**3 / (64.0 * math.pi)


def ufo_width_a_to_aa(
    m_a_gev: float,
    fa_gev: float,
    kb: float,
    kw: float,
    aewm1: float = DEFAULT_AEWM1,
) -> float:
    """Gamma(a -> gamma gamma) implied directly by the UFO's decays.py expression."""
    g_agg = g_agg_width_from_ufo(fa_gev, kb, kw, aewm1)
    return width_a_to_aa(m_a_gev, g_agg)


def dependent_mw_gev(aewm1: float = DEFAULT_AEWM1, m_z_gev: float = DEFAULT_MZ_GEV, gf: float = DEFAULT_GF) -> float:
    """Return the UFO's dependent W mass from aEWM1, MZ, and Gf."""
    aew = alpha_em(aewm1)
    discriminant = m_z_gev**4 / 4.0 - (aew * math.pi * m_z_gev**2) / (gf * math.sqrt(2.0))
    return math.sqrt(m_z_gev**2 / 2.0 + math.sqrt(discriminant))


def weak_mixing(aewm1: float = DEFAULT_AEWM1) -> tuple[float, float]:
    """Return (sw2, cw2) using the UFO's tree-level dependent MW."""
    mw_gev = dependent_mw_gev(aewm1)
    cw2 = mw_gev**2 / DEFAULT_MZ_GEV**2
    sw2 = 1.0 - cw2
    return sw2, cw2


def photophilic_k_split(k_sum: float, aewm1: float = DEFAULT_AEWM1) -> tuple[float, float]:
    """Split KB+KW so the UFO's tree-level gamma-Z-ALP coupling vanishes."""
    sw2, cw2 = weak_mixing(aewm1)
    return k_sum * cw2, k_sum * sw2


def manual_k_split(k_sum: float, kb_fraction: float) -> tuple[float, float]:
    if not 0.0 <= kb_fraction <= 1.0:
        raise ValueError("--kb-fraction must be between 0 and 1")
    kb = kb_fraction * k_sum
    kw = (1.0 - kb_fraction) * k_sum
    return kb, kw


def format_param(value: float) -> str:
    return f"{value:.12e}"


def build_param_card(
    *,
    m_a_gev: float,
    fa_gev: float,
    kb: float,
    kw: float,
    kg: float = 0.0,
    cta: float = 0.0,
    cb: float = 0.0,
    ct: float = 0.0,
    aewm1: float = DEFAULT_AEWM1,
    width_mode: str = "physical",
) -> str:
    g_agg = g_agg_from_ufo(fa_gev, kb, kw, aewm1)
    mw_gev = dependent_mw_gev(aewm1)
    if width_mode == "physical":
        walp = width_a_to_aa(m_a_gev, g_agg)
    elif width_mode == "stable":
        walp = 0.0
    else:
        raise ValueError("width_mode must be 'physical' or 'stable'")

    br_lines = ""
    if walp > 0.0:
        br_lines = "\n#          BR         NDA  ID1  ID2\n     1.000000e+00      2    22   22"

    return f"""######################################################################
## PARAM_CARD GENERATED BY mc/make_param_card.py
######################################################################
## Model: models/ALP_linear/SM_alp_UFO
## ALP particle: alp, PDG {ALP_PDG_ID}
## Effective coupling convention:
##   g_agg = alpha_em * (KB + KW) / (sqrt(2) * pi * fa)
##   alpha_em = 1 / aEWM1
## This is the Gate-1 associated-production normalization. The UFO's direct
## decay-width normalization is larger by sqrt(2) and is checked separately.
## Generated point:
##   m_a_GeV = {m_a_gev:.12g}
##   g_agg_GeV_inv = {g_agg:.12e}
##   fa_GeV = {fa_gev:.12g}
##   KB = {kb:.12g}
##   KW = {kw:.12g}
######################################################################

Block ALP
    1 {format_param(fa_gev)} # fa
    4 {format_param(cta)} # Cta
    9 {format_param(cb)} # Cb
   10 {format_param(ct)} # Ct
   11 {format_param(kg)} # Kg
   12 {format_param(kb)} # KB
   13 {format_param(kw)} # KW

Block CKMBLOCK
    1 2.277360000000e-01 # cabi

Block MASS
    1 5.040000000000e-03 # MD
    2 2.550000000000e-03 # MU
    3 1.010000000000e-01 # MS
    4 1.270000000000e+00 # MC
    5 4.700000000000e+00 # MB
    6 1.720000000000e+02 # MT
   11 5.110000000000e-04 # Me
   13 1.056600000000e-01 # MMU
   15 1.777000000000e+00 # MTA
   23 9.118760000000e+01 # MZ
   25 1.250000000000e+02 # MH
 {ALP_PDG_ID} {format_param(m_a_gev)} # Malp
   12 0.000000000000e+00 # ve
   14 0.000000000000e+00 # vm
   16 0.000000000000e+00 # vt
   21 0.000000000000e+00 # g
   22 0.000000000000e+00 # a
   24 {format_param(mw_gev)} # w+

Block SMINPUTS
    1 {format_param(aewm1)} # aEWM1
    2 1.166370000000e-05 # Gf
    3 1.184000000000e-01 # aS

Block YUKAWA
    1 5.040000000000e-03 # ymdo
    2 2.550000000000e-03 # ymup
    3 1.010000000000e-01 # yms
    4 1.270000000000e+00 # ymc
    5 4.700000000000e+00 # ymb
    6 1.720000000000e+02 # ymt
   11 5.110000000000e-04 # yme
   13 1.056600000000e-01 # ymm
   15 1.777000000000e+00 # ymtau

DECAY   6 1.508336490000e+00 # WT
DECAY  23 2.495200000000e+00 # WZ
DECAY  24 2.085000000000e+00 # WW
DECAY  25 4.070000000000e-03 # WH
DECAY {ALP_PDG_ID} {format_param(walp)} # Walp{br_lines}

Block QNUMBERS {ALP_PDG_ID} # alp
        1 0 # 3 times electric charge
        2 1 # number of spin states (2S+1)
        3 1 # colour rep (1: singlet, 3: triplet, 8: octet)
        4 0 # Particle/Antiparticle distinction (0=own anti)
"""


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Write an SM_alp_UFO param card for one ALP point.")
    parser.add_argument("--out", type=Path, required=True, help="Output param_card.dat path.")
    parser.add_argument("--m-a", type=float, required=True, help="ALP mass in GeV.")
    parser.add_argument("--g-agg", type=float, default=None, help="Physical g_agg in GeV^-1.")
    parser.add_argument("--fa", type=float, default=DEFAULT_FA_GEV, help="ALP decay constant in GeV.")
    parser.add_argument("--kb", type=float, default=None, help="Explicit UFO KB coefficient.")
    parser.add_argument("--kw", type=float, default=None, help="Explicit UFO KW coefficient.")
    parser.add_argument(
        "--kb-fraction",
        type=float,
        default=None,
        help=(
            "Manual fraction of KB+KW assigned to KB when --g-agg is used. "
            "Default uses the photophilic C_gammaZ=0 split."
        ),
    )
    parser.add_argument("--kg", type=float, default=0.0, help="UFO Kg coefficient.")
    parser.add_argument("--cta", type=float, default=0.0, help="UFO Cta coefficient.")
    parser.add_argument("--cb", type=float, default=0.0, help="UFO Cb coefficient.")
    parser.add_argument("--ct", type=float, default=0.0, help="UFO Ct coefficient.")
    parser.add_argument(
        "--aewm1",
        type=float,
        default=DEFAULT_AEWM1,
        help="Inverse electromagnetic coupling written to SMINPUTS. Default matches theory validation.",
    )
    parser.add_argument(
        "--width-mode",
        choices=("physical", "stable"),
        default="physical",
        help="Use the physical gamma-gamma width or make the ALP stable in the card.",
    )
    return parser.parse_args()


def main() -> None:
    args = _parse_args()
    if args.m_a <= 0:
        raise ValueError("--m-a must be positive")
    if args.fa <= 0:
        raise ValueError("--fa must be positive")

    if args.g_agg is not None:
        k_sum = k_sum_from_g_agg(args.g_agg, args.fa, args.aewm1)
        if args.kb_fraction is None:
            kb, kw = photophilic_k_split(k_sum, args.aewm1)
        else:
            kb, kw = manual_k_split(k_sum, args.kb_fraction)
    else:
        if args.kb is None or args.kw is None:
            raise ValueError("Provide either --g-agg or both --kb and --kw")
        kb, kw = args.kb, args.kw

    card = build_param_card(
        m_a_gev=args.m_a,
        fa_gev=args.fa,
        kb=kb,
        kw=kw,
        kg=args.kg,
        cta=args.cta,
        cb=args.cb,
        ct=args.ct,
        aewm1=args.aewm1,
        width_mode=args.width_mode,
    )
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(card)

    g_agg = g_agg_from_ufo(args.fa, kb, kw, args.aewm1)
    width = 0.0 if args.width_mode == "stable" else width_a_to_aa(args.m_a, g_agg)
    print(f"Wrote {args.out}")
    print(f"m_a_GeV={args.m_a:.12g}")
    print(f"fa_GeV={args.fa:.12g}")
    print(f"KB={kb:.12g}")
    print(f"KW={kw:.12g}")
    print(f"g_agg_GeV_inv={g_agg:.12e}")
    print(f"Walp_GeV={width:.12e}")


if __name__ == "__main__":
    main()
