ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SM_alp_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_4 = ', GC_4
      WRITE(*,2) 'GC_17 = ', GC_17
      WRITE(*,2) 'GC_40 = ', GC_40
      WRITE(*,2) 'GC_43 = ', GC_43
      WRITE(*,2) 'GC_45 = ', GC_45
